apiVersion: v1
kind: Namespace
metadata:
  name: exoplanet-detection
  labels:
    name: exoplanet-detection
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: exoplanet-quota
  namespace: exoplanet-detection
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "10"
    configmaps: "10"